### ISSUE TITLE
Mastodon -> Bluesky

### ISSUE THREAD

**Issue by poyoyoyoyo** [snarfed/bridgy-fed#1540] opened 2024-11-22 00:19 UTC
Mastodon users' postings to Bluesky do not seem to have been reflected since the night of November 20.
Are you currently experiencing problems?

**Comment by snarfed** [comment] 2024-11-22 01:21
Sorry, yes, Bluesky themselves are: #1520

**Comment by snarfed** [comment] 2024-11-22 01:21
Duplicate of #1520

**Closed by snarfed** 2024-11-22 01:21 UTC

**Comment by poyoyoyoyo** [comment] 2024-11-22 01:26
Thanks for your time. I will wait patiently.
