### ISSUE TITLE
Not mirroring posts from AP to AT

### ISSUE THREAD

**Issue by lambda** [snarfed/bridgy-fed#1539] opened 2024-11-21 23:13 UTC
I decided to opt into the bridge by following the account, and it looks like my profile was mirrored over to Bluesky: https://bsky.app/profile/unlambda.hachyderm.io.ap.brid.gy

However, none of my posts have been mirrored over, I made several since setting up the bridge to test it out.

Not sure if this is the right place to report this, so if there's a better place to do so, let me know. I figure given the rapid growth of Bluesky, it might be a bit backed up, but it's been nearly 24 hours. Is there any kind of queue status to learn more about what's going on?

**Comment by asonix** [comment] 2024-11-21 23:23
Would like to add that none of the posts I've made in the last day have been mirrored onto my bsky profile despite the bridge marking them as delivered. I wonder if this is bsky messing up or if the bridge is having problems

**Comment by snarfed** [comment] 2024-11-21 23:24
Bluesky is currently working on their relay, https://github.com/snarfed/bridgy-fed/issues/1520#issuecomment-2492534380, so they've temporarily turned off ingesting data from federated PDSes like Bridgy Fed. 😕 Sorry for the trouble. Hopefully they'll switch that back on soon!

**Comment by snarfed** [comment] 2024-11-21 23:24
Duplicate of #1520

**Closed by snarfed** 2024-11-21 23:24 UTC
