### ISSUE TITLE
migrating a bridged mastodon account?

### ISSUE THREAD

**Issue by alien-sunset** [snarfed/bridgy-fed#1462] opened 2024-11-10 00:07 UTC
I'm probably searching wrong but I'm having difficulty finding and answer:

what happens when a bridged mastodon account migrates to a new instance?

I have a bot account on botsin.space that will need to be migrated soon, and it's currently being bridged to bluesky, and I would like to not break that account if possible, especially if it does break there's no way for me to manually go in and post to it to let people know that the account has moved to a new address (and i won't be able to post from masto, because botsin.space will be going read only).

I also don't want to have to create a new actual bluesky account for the bot, because once again, I won't be able to post to the existing bluesky account to let people know or make pinned posts to keep any announcement to the top while the bot is still functioning. and since i haven't received an answer to a previous question about what happens to bridged account when the bridge breaks, I'm going to assume that the zombie bridge will just sit there, taking up space and accumulating followers that will inevitably be disappointed becasu they won't know that the bot now lives elsewhere or how to find it.

**Comment by snarfed** [comment] 2024-11-10 00:34
Hi! Sadly Bridgy Fed doesn't yet support fediverse account migration like this. Details in #330, feel free to follow there for updates. Sorry for the bad news.

Fortunately, https://muffinlabs.com/posts/2024/10/29/10-29-rip-botsin-space/ says botsin.space won't go read only until 12/15 or later, so you hopefully have plenty of time to choose where you plan to migrate and post that so that your account's followers in Bluesky see it.

Another thing you might consider is [setting a custom domain handle for your bridged Bluesky account](https://fed.brid.gy/docs#bluesky-enhanced), and then when you migrate and bridge your new fediverse account, set that same domain handle on the new account. That will hopefully help your Bluesky followers know that the new account is still you.

**Comment by alien-sunset** [comment] 2024-11-10 00:48
Ah, but to set a custom domain, I suppose I would need to OWN a custom domain, and I have not the money for such things

**Comment by alien-sunset** [comment] 2024-11-10 00:52
Also I noticed still no comment on what happens to disconnected bridges, sitting there all zombie like with an account’s face and info

**Comment by snarfed** [comment] 2024-11-10 00:56
Right. Sorry! As I mentioned, fediverse account migration isn't supported right now. You can always bridge your new account though, and if you have access to the old account before its instances goes down, you can block @bsky.brid.gy@bsky.brid.gy to disable the bridged account. Otherwise, I'm happy to do it manually.

Also, there are lots of free subdomain handle providers for Bluesky! https://www.skyname.io/ , https://handles.domi.zip/ , https://swifties.social/ , etc. And also lots of cheap TLDs that you can get domains for $1 or less per year, https://www.ionos.com/domains/cheap-domain-names , https://www.namecheap.com/domains/#pricing , etc.

**Comment by alien-sunset** [comment] 2024-11-10 01:09
What does blocking the brid.gy account DO though?  What happens to that bridge account on bluesky?

**Comment by snarfed** [comment] 2024-11-10 03:38
It deactivates the bridged Bluesky account. You can reactivate it later if you want by unblocking and re-following @bsky.brid.gy@bsky.brid.gy.

**Comment by alien-sunset** [comment] 2024-11-10 04:16
and if I don't want to reactivate it?
if I want it deleted?

**Comment by alien-sunset** [comment] 2024-11-10 05:12
also, I can't actually make any posts to Bsky that aren't automated posts, becasu botsin.space marks all posts for the next 6 hours after the first as private, and my bot auto posts every six hours, so any non automatic posts will not show up on bluesky unless I stop auto posting, which defeats the purpose of the bot, JUST to make a post specifically to bluesky, which I will only be able to do once per six hours, and won't be able to pin to the bluesky account, so in effect I have to take my bot offline, then hope that everybody following teh bot on bluesy actually sees that post becasu i won't be able to pin it.   all because ??? you want to be able to hold sole control over bridged accounts? gods forbid people actually be able to control their own content, this service is starting to sound suuuuper sus right about now.

**Comment by Tamschi** [comment] 2024-11-10 10:01
More precisely this is #1442 for tracking fediverse migrations. Pinning posts is #1374. Like on/off migrations of bridge accounts, the features are on our radar, but simply need more time due to limited resources for this project.

(We should definitely mark the bridge account as deleted on Bluesky and disassociate the DID and handle when we receive a `Delete` for a (currently or formerly) bridged account on the fediverse though. I'll file an issue for that in a moment, as this is effectively a regression due to the fix for #1130 if I'm not mistaken.)

Giving people direct control of their bridge accounts would come with a range of organisational, safety and legal concerns that likely aren't feasible for this project as-is. (Bridgy Fed would have to act as a content host rather than as proxy.)
You can read more about the nature of the project here: [Possible futures for Bridgy Fed](https://snarfed.org/2024-11-01_53932)

**Comment by snarfed** [comment] 2024-11-11 02:10
Thank you @Tamschi! @alien-sunset, I definitely get how your bot account's setup, plus botsin.space shutting down, plus Bridgy Fed's design all combine together to make this migration difficult and not what you want. I'm sorry, I wish I had a better answer for you.

As @Tamschi mentioned, some of what you want here - pinned posts, more support for fediverse account migration, more control over data deletion - are on our roadmap. I don't have an ETA, but we're not against them, we're very open to adding them eventually.

Others, notably manual control over bridged accounts, are unlikely due to the project's design and goals. All I can give you is my word, but trust me, I have no interest in controlling other people's accounts or data. I never expect to make any money from Bridgy Fed; any "control" I might seem to have is only downside and liability for me. I'm just trying to keep the scope here manageable, and avoid overburdening the project (and me) so that it doesn't collapse under its own weight.

**Comment by alien-sunset** [comment] 2024-11-11 04:22
thanks, this def wasn't what i was hoping, but [Tamschi](https://github.com/Tamschi)'s response does help me understand better.
i guess I should look at is as a good challenge to learn how to post to both Bluseky and Masto directly from my bot. 💜

**Comment by Tamschi** [comment] 2024-11-15 20:51
Since alien-sunset created a new Bluesky account for the bot (https://github.com/snarfed/bridgy-fed/issues/1137#issuecomment-2471433188) and all issues that came up are tracked elsewhere, I'll go ahead and close this one as duplicate.

**Closed by Tamschi** 2024-11-15 20:51 UTC
Labels: see other
