### ISSUE TITLE
Federate me please

### ISSUE THREAD

**Issue by Pawlicker** [snarfed/bridgy-fed#870] opened 2024-02-13 18:11 UTC
Hi, I am here to actually show support for this project. 

With all the "finest" of Mastodon/BlueSky showing their support by complaining that a federated social network is indeed, federating, I am here to say that I am in support of a social media network that is federating actually federating. Why? Well put it this way. Every single time you opt out, Elon Musk always wins. After all the nostr bridge has been up and the only thing that's happened is Nostr users have something to talk about that isn't solely "zap me pls". 

To quote one furry artist, "why would I use Bluesky and get 2 likes when I can get 100 on Twitter?" In fact, look how many people leave the network when they complain about server blocks without knowing it's the blocks keeping them off the network. This was literally in a server I'm in the other day so I'm not making stuff up.

![image](https://github.com/snarfed/bridgy-fed/assets/92184373/9f833b4c-4add-477a-b9d6-1bbb93f3e0bf)

Thanks for reading this and please watch Digimon Tamers subbed.

**Comment by pixiekat** [comment] 2024-02-13 18:16
Agreed. It's amazing how so many don't get the concept of ActivityPub, which is made to provide interoperability with other sites.

**Comment by Ashdemai** [comment] 2024-02-13 18:28
+1

**Comment by AshWeststar** [comment] 2024-02-13 18:37
+1

**Comment by Varpie** [comment] 2024-02-13 19:17
I'm all for having Bluesky implement ActivityPub, or creating a software that implements both Bleusky's AT procotol and ActivityPub. This, however, is not the way.

If the full ActivityPub specification was implemented, it would allow bridges to reflect the posts with the same state as they currently have in the origin server, which means if something gets edited, it will be edited quickly, and if something gets deleted, it will be deleted as well.
This bridge doesn't have anything to delete posts. It is essentially creating an archive that doesn't respect the user's desire to modify or delete their posts, or even their profile if they want to.

And since it's opt out, you have to know about it to avoid it, which is definitely not the way to go. Just like I don't want my data to be scraped by big companies that don't care about my rights, I also don't want my data to be scraped by a random "bridge" to somewhere I don't know about.

**Comment by AshWeststar** [comment] 2024-02-13 19:58
> If the full ActivityPub specification was implemented, it would allow bridges to reflect the posts with the same state as they currently have in the origin server, which means if something gets edited, it will be edited quickly, and if something gets deleted, it will be deleted as well.

In my opinion it doesn't matter because there are already ActivePub servers that support functionality to ignore deletes, edits etc. If this were a real problem, this would have been addressed in existing ActivePub server stacks.

**Comment by Varpie** [comment] 2024-02-13 20:06
> In my opinion it doesn't matter because there are already ActivePub servers that support functionality to ignore deletes, edits etc. If this were a real problem, this would have been addressed in existing ActivePub server stacks.

Oh yeah sorry, it's not a problem because others do it too. It's fine guys, we can burn everything down because others already do it, let's go!
This is the dumbest argument. Let's not contribute to making a product better, because there are worse options...

**Comment by AshWeststar** [comment] 2024-02-13 20:08
> Oh yeah sorry, it's not a problem because others do it too.

It's not a real problem because it's not addressed in any notable ActivePub stack, you're allowed to reject deletes intentionally. You're just coming up with excuses.

**Comment by Varpie** [comment] 2024-02-13 20:20
> It's not a real problem because it's not addressed in any notable ActivePub stack, you're allowed to reject deletes intentionally.

Once again: no, the specification says "the server receiving the delete activity SHOULD remove its representation of the object with the same id, and MAY replace that representation with a Tombstone object."
The word SHOULD is defined according to RFC 2119, and it means that "there may exist valid reasons in particular circumstances to ignore a particular item, but the full implications must be understood and carefully weighed before choosing a different course".
So it is not allowed to "reject deletes intentionally", unless you have a valid reason to (in which case the spec provides an option, which is to replace it with a Tombstone).
Every notable ActivityPub stack (that I know of) implements it correctly, in this case they didn't even try, so it is not standard compliant.

> In my opinion it doesn't matter because there are already ActivePub servers that support functionality to ignore deletes, edits etc.
>You're just coming up with excuses.

🤔

**Comment by coreyreichle** [comment] 2024-02-13 20:43
> > Agreed. It's amazing how so many don't get the concept of ActivityPub, which is made to provide interoperability with other sites.
> 
> I think once the bridge is up people will reconsider, like with Mastodon and search. For context, Mastodon search was deliberately broken and then turned to opt-in when artists were **extremely vocal** about discoverability being garbage on Mastodon, especially when search works on misskey and the like.
> 
> Now imagine artists on Bluesky getting follows from other fedi users. They're going to stay on Bluesky or other federated platforms as a result, IMO. They'll get more reposts instead of just 2.

Most people did NOT opt in to search, on my instance, I know that.  And yes, if this was opt-in, that would likely be acceptale.  The problem is that choice isn't presented.  Its "Opt Out", which is the crux of people's issues.

We, as in a large community of members, who have been on the "Fediverse" since it was Friendi.ca and Diasp*ra, only.  We came here to escape corporatized social media.  And we do not have any interested in feeding LLMs with our content for free, we have no interest in the pileups that occur on corporate social media, and we have no interest in assisting a flailing social media service like BSky appear more relevant.

**Comment by coreyreichle** [comment] 2024-02-13 21:00
> nostr has federated with mostr.pub (a bridge between AP and a competing blockchain social network called nostr) and nothing bad has happened. If anything, it's made discussion thrive.

That, alone, is a bad thing.  It's caused the ponzicoin discussions on the fediverse to proliferate.

> Also atproto isn't some walled garden like Threads is that's federating with the rest of the web, but a different protocol entirely. Their entire codebase is on Github.

It is a walled garden until it's actually opened up.  If it weren't a walled garden, then BSky would have made their proprietary protocol an official spec, and compatible with existing official specs (ie, AP).

Its a walled garden, doing poorly, which is why there's a push to suck in content from elsewhere.

**Comment by Pawlicker** [comment] 2024-02-13 21:08
> > nostr has federated with mostr.pub (a bridge between AP and a competing blockchain social network called nostr) and nothing bad has happened. If anything, it's made discussion thrive.
> 
> That, alone, is a bad thing. It's caused the ponzicoin discussions on the fediverse to proliferate.

And not the spambots on say, Mastodon.social that were there a few months back because regs there are open? A lot of fedi spam and low-quality posts come from instances with open regs, and this has affected several instances. 

> > Also atproto isn't some walled garden like Threads is that's federating with the rest of the web, but a different protocol entirely. Their entire codebase is on Github.
> 
> It is a walled garden until it's actually opened up. If it weren't a walled garden, then BSky would have made their proprietary protocol an official spec, and compatible with existing official specs (ie, AP).
> 
> Its a walled garden, doing poorly, which is why there's a push to suck in content from elsewhere.

The protocol is documented. I'm not a Bluesky/Atproto fanboy, but to call it "proprietary" simply because the flagship instance does not federate and there's little steam for running a PDS server outside Bluesky at this moment (which has been done from what I've been told) is misleading. 
https://arxiv.org/abs/2402.03239
https://atproto.com/docs

Most of the reason atproto was made, aside from perceived moderation issues, has to do with a massive chunk of the internet valuing their internet identities. Queer.af losing their domain (which is one of the first times it's happened to that side of the fedi, see neckbeard.xyz losing it's domain because of the TLD owners, how boks.moe was marked as a malware domain, etc.) made this conversation pop up again. There are a lot of people who see their posting history as something very important. Given how many Mastodon instances have died off since 2017 (and GS instances before that), this is a very important thing for a crowd used to Twitter "just working" even post-Elon Musk. Twitter doesn't lose domains or forget to pay the AWS/DigitalOcean bill. 

https://atproto.com/guides/faq

**Comment by ashqinmoe** [comment] 2024-02-13 21:57
As a photographer on Mastodon, I have had some great interactions with people via Mostr, the Nostr gateway for Mastodon and would really appreciate more federations like this. I would really like to federate with Bluesky users too.

**Comment by ashqinmoe** [comment] 2024-02-13 22:00
+1

**Comment by Varpie** [comment] 2024-02-13 22:01
> Delete rejecting is a very real thing that some instances do, especially as one popular instance stack openly supports it in the MRFs (while the intent is to avoid servers being hammered presumably by deletion spam, many instances use this to reject deletes from everyone and this is a very controversial issue). It is 100% not a hypothetical. The only "solution" is to set federation with said instances to followers only and the like. https://docs-develop.pleroma.social/backend/configuration/mrf/

You say it yourself: the intent is to avoid deletion spam, which respects the ActivityPub spec: it is a valid reason to ignore the delete activity. And like you say, rejecting deletes from everyone is a very controversial issue, for a good reason.
The problem here is that this bridge doesn't even try to implement deletes, which is detrimental: people having an auto-deletion policy in Mastodon for instance would end up having their posts persisted somewhere without their knowledge or consent.

I'm not against the AT proto itself, as I've said I would like a software that implements both the AT proto and ActivityPub, but having a half-assed non-compliant implementation that doesn't include a way to block the instance and doesn't respect update/delete operations is a big fat no for me.

**Comment by AshWeststar** [comment] 2024-02-13 22:25
Bruh, @Varpie go make a dedicated issue for your issue so it can be addressed instead of hijacking a thread not dedicated to your issue.

**Comment by CallistaAI** [comment] 2024-02-13 23:02
Hi. Im a transfemme from bluesky. Id like to correct some misconceptions about the place said in other threads. There are in fact a lot of trans people on bluesky, in fact trans people are the politically dominant group. Trans people run the popular moderation services, and a number of the custom feeds. Most of us are utterly indifferent to mastodon in just about every way. Personally I don't care who does and doesn't bridge with bluesky, that's up to you all.  Jack Dorsey doesn't actually have any power on bluesky and we ran him off and he cries about it on nostr. Almost all of the rhetoric about bluesky mastodon goes on about is wrong, we do hear about it when it hits a peak, but we just laugh because of how obviously untrue it all is. Were just people talking to other people, just like you all.

Theres been no push from our end to bridge this and it comes to our surprise just like it came to yours.

**Comment by gentleAmateur** [comment] 2024-02-14 00:10
Chad Digimon Enjoyer

**Comment by iskamag** [comment] 2024-02-14 00:37
Catposter approved
![f95be595f4cb4e9c](https://github.com/snarfed/bridgy-fed/assets/49951677/69ae0281-a4c4-4bc4-826d-e3e21815dd8c)

**Comment by temtemy** [comment] 2024-02-14 02:00
> The problem here is that this bridge doesn't even try to implement deletes

The [documentation](https://fed.brid.gy/docs#router) says it does?

> Jack Dorsey doesn't actually have any power on bluesky and we ran him off and he cries about it on nostr.

@CallistaAI Yeah I heard about this somewhere, though IIRC isn't he still in the board of directors?

**Comment by temtemy** [comment] 2024-02-14 02:01
> The problem here is that this bridge doesn't even try to implement deletes

@Varpie The [documentation](https://fed.brid.gy/docs#router) says it does?

> Jack Dorsey doesn't actually have any power on bluesky and we ran him off and he cries about it on nostr.

@CallistaAI Yeah I heard about this somewhere, though IIRC isn't he still in the board of directors?

**Comment by CallistaAI** [comment] 2024-02-14 02:07
> > The problem here is that this bridge doesn't even try to implement deletes
> 
> The [documentation](https://fed.brid.gy/docs#router) says it does?
> 
> > Jack Dorsey doesn't actually have any power on bluesky and we ran him off and he cries about it on nostr.
> 
> @CallistaAI Yeah I heard about this somewhere, though IIRC isn't he still in the board of directors?

I think so but he does not actually show up to meetings and hasn't for a very long time. He literally has no power over the website and ragequit it because nobody would listen to him and we dogpiled his ass on bluesky every time he posted. The staff did not intervene at all when we melted his ass off the site. Jay, the CEO is actually a nice lady. You know, for a CEO. 

Look we dont care if you use mastodon and not bluesky, you can use whatever sites you want to it doesnt matter to us. I do wish people would stop lying about the site to justify not joining it. If its not for you its not for you its not a moral imperative,

**Comment by therealNAAN** [comment] 2024-02-14 07:18
> Hi. Im a transfemme from bluesky. Id like to correct some misconceptions about the place said in other threads. There are in fact a lot of trans people on bluesky, in fact trans people are the politically dominant group. Trans people run the popular moderation services, and a number of the custom feeds. Most of us are utterly indifferent to mastodon in just about every way. Personally I don't care who does and doesn't bridge with bluesky, that's up to you all. Jack Dorsey doesn't actually have any power on bluesky and we ran him off and he cries about it on nostr. Almost all of the rhetoric about bluesky mastodon goes on about is wrong, we do hear about it when it hits a peak, but we just laugh because of how obviously untrue it all is. Were just people talking to other people, just like you all.
> 
> Theres been no push from our end to bridge this and it comes to our surprise just like it came to yours.

This was bonkers to me that folks on Mastodon would say this. As someone who will not be on Bluesky anytime soon, even I knew this months ago.

+1 to you.

**Comment by therealNAAN** [comment] 2024-02-14 07:21
Digimon Tamers is great, and one day I will watch it subbed.

A friend brought up safety notions with this bridge (mainly API stuff, Google Cloud use) which I think are sound aspects. That said, if this all ends up being kosher, stable, secure and all those other adjectives, I hope this goes through. My instance has silenced/limited the bridge and is very open/alert to any news about the bridge, so thankfully I won't be in a drastic situation.

**Comment by Cyberes** [comment] 2024-02-15 00:00
Very cool everyone. Let's link these issues together https://github.com/snarfed/bridgy-fed/issues/879

**Comment by snarfed** [comment] 2024-02-15 20:30
> > The problem here is that this bridge doesn't even try to implement deletes [or edites]
> 
> @Varpie The [documentation](https://fed.brid.gy/docs#router) says it does?

@temtemy is right, translating AP `Delete` and `Update` activities has been implemented here for years, both in and out. The Bluesky part of the bridge hasn't been implemented yet, so the docs for it specifically aren't up yet, but I'll make sure they are well before launch.

Otherwise, thanks @Pawlicker and everyone else for quite the wide-ranging thread.

**Closed by snarfed** 2024-02-15 20:30 UTC
