### ISSUE TITLE
Post Deletion on Mastodon Fails to Propagate to Bluesky

### ISSUE THREAD

**Issue by tonilijic** [snarfed/bridgy-fed#1494] opened 2024-11-16 05:46 UTC
Occasionally, I make small typos that I only notice after publishing a post on Mastodon. When that happens, I delete the post right away and publish a corrected version with similar content. Sometimes, I repeat this process multiple times, so it’s understandable if the bot gets confused.

The issue I’m encountering is that some of the posts I’ve deleted on Mastodon—which no longer exist there—are still appearing on my Bluesky account. Here are a few examples:

- [https://bsky.app/profile/toni.li/post/3laz354hzfib2](https://bsky.app/profile/toni.li/post/3laz354hzfib2)

- [https://bsky.app/profile/toni.li/post/3l6zlyfq4hf22](https://bsky.app/profile/toni.li/post/3l6zlyfq4hf22)

- [https://bsky.app/profile/toni.li/post/3l73sofdtbo22](https://bsky.app/profile/toni.li/post/3l73sofdtbo22)

**Comment by snarfed** [comment] 2024-11-16 06:10
Sounds like this is #1361. Definitely worth fixing! But it's going to take some thought, we don't have an easy answer yet.

**Comment by tonilijic** [comment] 2024-11-16 06:55
Wow that was much quicker response than expected. No rush, just trying to be of help. Appreciate what you guys have done so far!

**Comment by Tamschi** [comment] 2024-11-16 07:06
Closing as duplicate of #1361.

**Closed by Tamschi** 2024-11-16 07:06 UTC
Labels: see other
