### ISSUE TITLE
Returning 400: Target post https://mastodon.technology/@snarfed/3194674 has no Atom link

### ISSUE THREAD

**Issue by sparxsys** [snarfed/bridgy-fed#68] opened 2020-09-02 06:57 UTC
Hello,

I am trying to setup this on my Drupal site using Indieweb module. 

Source: https://www.ravisagar.in/reply/trying-send-webmention-again-mastadon
Target: https://mastodon.social/@swentel/100776214865184909

**Error:** 

I 2020-09-02 06:45:13.381355 Response source target: https://www.ravisagar.in/reply/trying-send-webmention-again-mastadon https://mastodon.social/@swentel/100776214865184909
I 2020-09-02 06:45:13.383153 Returning 400: Target post https://mastodon.social/@swentel/100776214865184909 has no Atom link
E 2020-09-02 06:45:13.454242 Error 400, response body: '400 Bad Request\n\nThe server could not comply with the request since it is either malformed or otherwise incorrect.\n\n Target post https://mastodon.social/@swentel/100776214865184909 has no Atom link  '

I have done the setup as mentioned on this page: https://fed.brid.gy/. I believe my atom feed is fine. Also I created .well-known folder and added these lines in the .htaccess

> RewriteEngine on
>   RewriteBase /
>   RewriteRule ^.well-known/(host-meta|webfinger).* https://fed.brid.gy/$0  [redirect=302,last]

Not sure what I am missing here so raising an issue. I might have missed some configuration but my site is sending the webmention which I can also see in the logs: https://fed.brid.gy/responses

Thanks for the great application :)

**Comment by snarfed** [comment] 2020-09-03 05:25
hmm! sorry for the trouble. not sure what's going on here, but i'll take a look soon.

**Comment by snarfed** [comment] 2020-09-06 16:39
to add a bit of context here, [based on the log](https://fed.brid.gy/log?key=https%3A%2F%2Fwww.ravisagar.in%2Freply%2Ftrying-send-webmention-again-mastadon+https%3A%2F%2Fmastodon.social%2F%40swentel%2F100776214865184909&start_time=1599030271), Bridgy Fed first tried to reply via ActivityPub, which is the protocol that Mastodon supports. it sent a valid AP request, but Mastodon returned an error. Bridgy Fed then tried to fall back to OStatus, which is why it complained that https://mastodon.social/@swentel/100776214865184909 (not your own post) "has no Atom link."

the real question is, why did mastodon.social fail a (seemingly) perfectly good AP request. i'll keep looking.

**Comment by sparxsys** [comment] 2020-09-06 18:16
Thanks for looking into this :)

**Comment by snarfed** [comment] 2020-10-21 22:35
argh, sorry for the trouble, and thanks for the nudge! i'll look at this again.

**Comment by nekr0z** [comment] 2020-10-22 04:54
Thing is, I have successfully used Bridgy Fed for quite a while to interact with that very Mastodon instance. Either they pushed some Mastodon update that broke things, or it's some corner case I've just hit.

**Comment by snarfed** [comment] 2020-10-22 19:53
@nekr0z interesting. when bridgy fed sends mastodon.social this AP `Create` request for your reply:

```json
{
  "@context": "https://www.w3.org/ns/activitystreams";,
  "type": "Create",
  "object": {
    "published": "2020-10-21T20:13:17+0300",
    "content": "<p>While I do totally agree with you about the lack of the due process and the general stupidity of mandating masks outdoors, I \u2014 as a privacy-loving citizen \u2014 have a confession to make: I\u2019m glad COVID-19 brought these mask-wearing rules, and I think it will be one of the things I\u2019ll remember 2020 fondly for.</p>\n<p>There\u2019s a Federal Law in Russia (and a Federal Law is, like, a big deal) \u201cAbout gatherings, meetings, demonstrations, processions, and picketings\u201d, and in that Federal Law there\u2019s a clause that says a participant of a public event is not allowed to cover or hide his/her face. And the Administrative Offences Code ... Russia (not the Criminal Code, ... bad, too) says violating the legal rules of participating in a public event is grounds to a fine or up to 40 hours of public works. So you basically don\u2019t want to cover your face in a public event, really. A lot of countries have similar regulations, but\u2026</p>\n<p>But I live in Moscow, and Moscow is quite unlike the rest of Russia in many ways (I used to live in St.-Petersburg for 6 years, and I\u2019m originally from Kaliningrad aka K\u00f6nigsberg in Pr. where a big part of my family still lives, so I have grounds to compare). While it\u2019s true Moscow has much more money, power, and opportunities than the rest of Russia combined, living in Moscow also has its drawbacks. And besides traffic and bad air, Moscow also houses the Federal Government, the Parliament (both Houses), and the President of Russia, and these people seem to really hate the idea of public unrest. It\u2019s hard to blame them, history seems to attest that public unrest in Russia tends to be bloody and unfortunate for those in power. Anyway, the people currently in power seem to be very scared of what might happen, so Moscow police tend to be very repressive and harsh, and Moscow courts of law have even less rulings in favour of the defendant that the Russian average (which is, I believe, less than 1% anyway).</p>\n<p>So for years now I\u2019ve been advised by layers to try and avoid covering my face in public places, in malls, on the subway, etc. \u2014 you never know what they\u2019ll call a gathering (hence a public event), and you can never prove you didn\u2019t aim to avoid recognition, especially in a country where any evidence from a defendant that a police officer is giving a false accusation can be dismissed because \u201ccourt has no reason to doubt the words of an officer of the law\u201d (yep, Moscow courts use that a lot).</p>\n<p>With COVID-19 they banned public events altogether (which is very bad, of course), but I\u2019m no longer afraid to go out with my face covered. Which is ultimately a good thing privacy-wise in my book\u2026</p>\n<p>And thank you for the podcast \u2014 again! Please do continue!</p>",
    "url": "https://fed.brid.gy/r/https://evgenykuznetsov.org/en/reactions/2020/face-masks/";,
    "inReplyTo": "https://fed.fab.industries/users/fabsh/statuses/105069505860853845";,
    "@context": "https://www.w3.org/ns/activitystreams";,
    "type": "Note",
    "attributedTo": [
      {
        "url": "https://fed.brid.gy/r/https://evgenykuznetsov.org";,
        "type": "Person",
        "name": "Evgeny Kuznetsov",
        "image": [
          {
            "url": "https://evgenykuznetsov.org/img/avatar.jpg";,
            "type": "Image",
            "name": "Evgeny Kuznetsov"
          }
        ],
        "icon": [
          {
            "url": "https://evgenykuznetsov.org/img/avatar.jpg";,
            "type": "Image",
            "name": "Evgeny Kuznetsov"
          }
        ],
        "preferredUsername": "evgenykuznetsov.org",
        "id": "https://fed.brid.gy/evgenykuznetsov.org";
      }
    ],
    "tag": [
      {
        "type": "Mention",
        "href": "https://fed.fab.industries/users/fabsh";
      }
    ],
    "id": "https://fed.brid.gy/r/https://evgenykuznetsov.org/en/reactions/2020/face-masks/";,
    "cc": [
      "https://www.w3.org/ns/activitystreams#Public";,
      "https://fed.fab.industries/users/fabsh";,
      "https://fed.fab.industries/users/fabsh/followers";
    ]
  }
}
```

...mastodon.social responds with: 
```
HTTP 401
Client Error: Unauthorized for url: https://fed.fab.industries/users/fabsh/inbox
```

not sure why yet.

**Comment by snarfed** [comment] 2020-10-22 19:57
maybe fed.fab.industries is configured to block replies somehow? cc @fabsh...?

**Comment by snarfed** [comment] 2020-10-22 20:46
401 implies that the HTTP `Signature` header is bad or isn't getting accepted. i haven't changed the way bridgy fed generates that recently, but evidently mastodon 3.2.1 - which fed.fab.industries runs - evidently changed their handling of it. from https://github.com/tootsuite/mastodon/releases/tag/v3.2.1 :

> [Add support for latest HTTP Signatures spec draft](https://github.com/tootsuite/mastodon/pull/14556)
> ...
> [Fix dereferencing remote statuses not using the correct account for signature when receiving a targeted inbox delivery](https://github.com/tootsuite/mastodon/pull/14656)

guess i need to dig in and understand what they changed.

**Comment by snarfed** [comment] 2020-10-22 20:48
looks like this is the culprit: https://github.com/tootsuite/mastodon/issues/15016

**Comment by snarfed** [comment] 2020-10-22 21:57
ok, i'm now including and signing the `Host` and `Digest` HTTP headers, as required by mastodon 3.2.1 (see https://github.com/tootsuite/mastodon/pull/14556#issuecomment-674077648), but i'm still getting a generic `401 Client Error: Unauthorized for url: ...` error back. i don't think it's due to the new req'ts, since while i was adding them and testing, i got specific error messages for them, eg `missing required header "digest"`. the generic error message makes me think something else is wrong. 🤷

**Comment by nekr0z** [comment] 2020-10-23 04:24
As I said before, Bridgy Fed did successfully pass my replies to that very Mastodon instance ([this one]( https://evgenykuznetsov.org/en/reactions/2020/fabsh-social-networks/), for example, just 4 days before things broke. And @fabsh does seem to be running 3.2.1 now (which mas released in the meantime), so whatever the issue is, it is very much likely related to that release. Not sure whether it's the same thing @sparxsys originally reported — there was no 3.2.1 back then.

**Comment by ThibG** [comment] 2020-10-23 11:54
@snarfed is there a way I can help with debugging that? The code in Mastodon 3.2.1 is indeed stricter than it used to be, but as you said, it should return specific error messages when an issue occur.

**Comment by snarfed** [comment] 2020-10-23 18:35
@ThibG thanks for offering! you're right, the specific error messages were definitely helpful. i worked through those, but i'm now getting the generic `401 Client Error: Unauthorized for url: ...` error, for a `Create` request posted to a user's inbox that succeeded before 3.2.1. [full JSON activity example here.](https://github.com/snarfed/bridgy-fed/issues/68#issuecomment-714725147)

i expect this means Mastodon couldn't verify the HTTP signature. i'm using the [httpsig](https://github.com/ahknight/httpsig) Python package to generate it, which was working before. any tips on debugging generic 401 errors from Mastodon like this? (apart from installing and testing Mastodon locally, which I'm not quite ready to commit to. 😁)

**Comment by ThibG** [comment] 2020-10-23 18:58
`401 Client Error: Unauthorized for url: ...` doesn't sound like something Mastodon itself would return. I'm surprised you wouldn't have a body with some more details.

You could try sending to `https://social.sitedethib.com/users/Thib/inbox`, I added some instrumentation on my end.

**Comment by snarfed** [comment] 2020-10-26 15:53
thanks for the nudge @ThibG! you're absolutely right, there was indeed a body with more detail. i thought i was logging it, but evidently not.

```
Verification failed for evgenykuznetsov.org@evgenykuznetsov.org https://fed.brid.gy/evgenykuznetsov.org using rsa-sha256 (RSASSA-PKCS1-v1_5 with SHA-256)
```

that confirms my hunch that this is a signature verification failure. still a bit confusing, since these signatures were succeeding with Mastodon before 3.2.1, but 🤷. i'll look at a few more things, and i may take you up on your offer of testing against social.sitedethib.com with its instrumentation. thanks again for helping!

**Comment by ThibG** [comment] 2020-10-26 16:14
Nothing should have changed regarding how the signatures are verified/computed. My hunch is that maybe, in signing more headers to please Mastodon's new requirements, you inadvertently added some header twice (e.g., `Host`), signing only one copy, but having it twice in the request?

**Comment by snarfed** [comment] 2020-10-26 20:53
Good hunch, thanks! Didn't pan out, but gave me some other ideas. I'll keep looking.

**Comment by swentel** [comment] 2020-10-29 11:09
Hah, I got hit by this one as well. I haven't got to the digest signing part yet, but I'll report back the changes in my Drupal AP module if I can get it working.

**Comment by swentel** [comment] 2020-10-29 20:49
@snarfed I got it working again for mastodon 3.2.1 adding the digest header, this is the commit in case it you're interested: https://git.drupalcode.org/project/activitypub/commit/0bdd562

**Comment by snarfed** [comment] 2020-10-29 23:10
thanks @swentel! yeah i did the same thing a bit earlier here, and finally committed and pushed it just now, d22903c3a75badd841c3aac6e6b053e4d4202fd7, but still no luck yet.

**Comment by ThibG** [comment] 2020-10-30 13:50
@snarfed I guess the body as serialized by requests might be different from what you actually sign? That's just a hunch, I have not tested your code. The offer to try on social.sitedethib.com/inbox is still up, and I've added a bit specific to the Digest header for debugging

**Comment by snarfed** [comment] 2020-10-30 20:57
@ThibG thanks again for the help! i definitely appreciate the instrumenting you set up on social.sitedethib.com, i may try it soon. i'll let you know.

**Comment by snarfed** [comment] 2020-10-31 21:03
ok @ThibG! i sent an AP activity to `https://social.sitedethib.com/users/Thib/inbox` a couple times just now, at 20:37:42 and 20:47:41 UTC. it had Date, Digest, and Host headers, and a Signature header that included them. full activity is below. let me know if you see anything obvious in your instrumentation. thanks again!

```json
{
  "published": "2020-10-31T13:37:22-07:00",
  "content": "likes <a class=\"u-like u-like-of\" href=\"https://social.sitedethib.com/@Thib/101878161113758535\">Claire: \u201cMy girlfriends are the most wonderful people ever\u2026\u201d \u2013 Mastodon (instance perso)</a>\n<cite class=\"via\"><a href=\"https://fed.brid.gy/\">via Bridgy Fed</a></cite>",
  "url": "https://fed.brid.gy/r/https://snarfed.org/2020-10-31_claire-my-girlfriends-are-the-most-wonderful-people-ever-mastodon-instance-perso",
  "actor": {
    "url": "https://fed.brid.gy/r/https://snarfed.org/",
    "type": "Person",
    "name": "Ryan Barrett",
    "image": [
      {
        "url": "https://secure.gravatar.com/avatar/947b5f3f323da0ef785b6f02d9c265d6?s=96&d=blank&r=g",
        "type": "Image"
      }
    ],
    "icon": [
      {
        "url": "https://secure.gravatar.com/avatar/947b5f3f323da0ef785b6f02d9c265d6?s=96&d=blank&r=g",
        "type": "Image"
      }
    ],
    "preferredUsername": "snarfed.org",
    "id": "https://fed.brid.gy/snarfed.org"
  },
  "@context": "https://www.w3.org/ns/activitystreams",
  "type": "Like",
  "object": "https://social.sitedethib.com/users/Thib/statuses/101878161113758535",
  "id": "https://fed.brid.gy/r/https://snarfed.org/2020-10-31_claire-my-girlfriends-are-the-most-wonderful-people-ever-mastodon-instance-perso",
  "cc": [
    "https://www.w3.org/ns/activitystreams#Public",
    "https://social.sitedethib.com/users/Thib",
    "https://social.sitedethib.com/users/Thib/followers"
  ]
}
```

**Comment by ThibG** [comment] 2020-10-31 21:44
Hmm, my instrumentation was lacking some info to debug that more easily, but it's definitely an issue with the Digest not matching, and I'm pretty sure it's because `json_dumps` and requests' `json` parameter do not actually result in exactly the same body. I'd suggest passing the result of `json_dumps` to requests.

**Comment by snarfed** [comment] 2020-10-31 22:31
thanks! you did mention that before, i should have tried it earlier. good idea, but no luck. tried just now, 22:24:12 UTC, same result. code in 199d4d6f63ce80620a0b346bc33b5f9b1618d0b0.

**Comment by ThibG** [comment] 2020-11-01 09:29
@snarfed ok found it, in your `Digest` header, you use “SHA256” while the expected algorithm name is “SHA-256”

**Comment by snarfed** [comment] 2020-11-01 16:08
hah, wow, great catch! single character typo bugs like that are the worst. thank you so much for your help! got a 202 from social.sitedethib.com this time, looks like that may have done the trick. 🎉

**Comment by nekr0z** [comment] 2020-11-02 04:41
I can confirm it's working for me now. Thank you!

**Closed** 2020-11-02 04:59 UTC

**Comment by fabsh** [comment] 2020-11-09 11:52
Hi! Just saw this now. Sorry I wasn't able to help, but glad to see you got it fixed.  👍
