### ISSUE TITLE
No longer posting to bluesky

### ISSUE THREAD

**Issue by benjifs** [snarfed/bridgy-fed#1620] opened 2024-12-12 20:17 UTC
I'm trying out a separate site that automatically posts to bsky and mastodon a few times a day. I only just noticed that while it has been successfully posting to AP, it stopped posting to bsky after the first few days.

https://fed.brid.gy/web/haiku.oom9.xyz
https://bsky.app/profile/haiku.oom9.xyz

Any suggestion on what to do to get posts to show up on bluesky?

**Comment by snarfed** [comment] 2024-12-13 01:30
Hey, sorry for the trouble! I've nudged your account, it may start working again now. If not, you may have fallen victim to #1595.

**Comment by snarfed** [comment] 2024-12-15 17:55
Looks like this didn't work. Sigh, sorry, #1595 it is.

**Comment by snarfed** [comment] 2024-12-15 17:55
Duplicate of #1595

**Closed by snarfed** 2024-12-15 17:55 UTC
