### ISSUE TITLE
profile failed to update, despite being marked as "delivered successfully"

### ISSUE THREAD

**Issue by jasm1nii** [snarfed/bridgy-fed#614] opened 2023-08-13 09:28 UTC
this happened after i followed my mas.to account from my bridgy fed account, then i tried pushing multiple updates to my h-card info that didn't go through. there were no logs generated with any of the subsequent profile updates, so this is the only thing i can show.

![image](https://github.com/snarfed/bridgy-fed/assets/67263692/10d7fdac-2613-4d44-a6ad-d34b0bd26b07)

**Comment by snarfed** [comment] 2023-08-13 22:19
Hmm, sorry for the trouble! Will look.

**Comment by snarfed** [comment] 2023-08-14 03:07
Hi again! Looking at https://mas.to/@jasmine@jasm1nii.xyz , it seems to match your h-card on https://jasm1nii.xyz/ . Is there something specific you're expecting to see that's not there?

**Comment by jasm1nii** [comment] 2023-08-14 03:11
it's not an exact match, there's a couple details i've changed since the last successful update. my profile picture was also set as my header, despite not having one specified.

**Comment by snarfed** [comment] 2023-08-14 03:33
Ah, right. It defaults your header to your profile picture if you don't set a different one explicitly: https://fed.brid.gy/docs#profile

Which details did it miss? Looking at the BF logs for the profile updates, eg the latest one today at 15:47:33 UTC, here's the mf2 it parsed out of your home page (basically the same as eg https://pin13.net/mf2/?url=https://jasm1nii.xyz/ ), and the AS2 profile object it delivered to mas.to.

mf2:
```json
{
  "type": [
    "h-card"
  ],
  "properties": {
    "photo": [
      {
        "value": "https://jasm1nii.xyz/assets/media/main/07042023 me.png",
        "alt": "a self portrait of the author wearing a hijab, glasses, jewelry, and a collared blouse; drawn against a pink background"
      }
    ],
    "note": [
      "\ud83d\udccd IDN \ud83c\udfa8 illustrator & multimedia designer \ud83d\udc18 @jasm1nii@mas.to"
    ],
    "url": [
      "acct:jasmine@jasm1nii.xyz",
      "https://jasm1nii.xyz/"
    ],
    "uid": [
      "https://jasm1nii.xyz/"
    ]
  }
}
```

AS2:
```json
{
  "id": "https://fed.brid.gy/r/https://jasm1nii.xyz/#update-2023-08-13T15:47:34.499697+00:00",
  "actor": "https://fed.brid.gy/jasm1nii.xyz",
  "@context": "https://www.w3.org/ns/activitystreams",
  "type": "Update",
  "object": {
    "id": "https://fed.brid.gy/jasm1nii.xyz",
    "summary": "\ud83d\udccd IDN \ud83c\udfa8 illustrator & multimedia designer \ud83d\udc18 @jasm1nii@mas.to",
    "url": [
      "https://fed.brid.gy/r/acct:jasmine@jasm1nii.xyz",
      "https://jasm1nii.xyz/"
    ],
    "image": {
      "url": "https://jasm1nii.xyz/assets/media/main/07042023 me.png",
      "type": "Image",
      "name": "a self portrait of the author wearing a hijab, glasses, jewelry, and a collared blouse; drawn against a pink background"
    },
    "updated": "2023-08-13T15:47:34.499660+00:00",
    "type": "Person",
    "attachment": [
      {
        "type": "PropertyValue",
        "name": "Web site",
        "value": "<a rel=\"me\" href=\"https://jasm1nii.xyz/\"><span class=\"invisible\">https://</span>jasm1nii.xyz<span class=\"invisible\">/</span></a>"
      },
      {
        "url": "https://jasm1nii.xyz/assets/media/main/07042023 me.png",
        "type": "Image",
        "name": "a self portrait of the author wearing a hijab, glasses, jewelry, and a collared blouse; drawn against a pink background"
      }
    ],
    "icon": {
      "url": "https://jasm1nii.xyz/assets/media/main/07042023 me.png",
      "type": "Image",
      "name": "a self portrait of the author wearing a hijab, glasses, jewelry, and a collared blouse; drawn against a pink background"
    },
    "preferredUsername": "jasm1nii.xyz",
    "publicKey": {
      "id": "https://fed.brid.gy/jasm1nii.xyz",
      "owner": "https://fed.brid.gy/jasm1nii.xyz",
      "publicKeyPem": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnyFvknXJvPHPEb2KWN32\n3H6ynKZQflXTVWrzRL845LHHhQLYBE++lTFdauAgB0HLs7rBwtyQQQ8Ka2U0bwmU\ndT/l87ZFi/y6JgskPWhzwTSRFpEwSvR1fJQqTuWnjqS0fkCpOA1JjnHaPjVJOn0+\nTVBzupItI79YctLY/yo8IGPRD1stzNfaD1vzDY5Q57JnZOYtuK/MsZ3zdbnlUpkq\nnQih9JMNdA1OJPx5goeYbRhs+ubWSoBGb1zAOkoeRo+KT2iGuwFYzquuduhc6Ez4\nBPNeH9F+zIxc9FYYtgwBhC+sMDzS/VZQJ1MEWlg9l+rHSzG8rcmUFbd59PY2VecL\nZwIDAQAB\n-----END PUBLIC KEY-----"
    },
    "@context": [
      "https://w3id.org/security/v1"
    ]
  },
  "to": [
    "https://www.w3.org/ns/activitystreams#Public"
  ]
}
```

**Comment by jasm1nii** [comment] 2023-08-14 04:27
okay yeah, this is correct, sadly i've yet to see this reflected on my end when i check the account on my mas.to instance...

**Comment by snarfed** [comment] 2023-08-14 04:38
Hmm, what specifically do you not see reflected? Just to confirm, this is what I see on https://mas.to/@jasmine@jasm1nii.xyz right now:

<img width="682" alt="image" src="https://github.com/snarfed/bridgy-fed/assets/778068/c866bda9-ea77-4283-83c5-9a5a0edf7b16">

**Comment by jasm1nii** [comment] 2023-08-14 04:44
it's in the first several lines of the AS2 profile object:

`{
  "id": "https://fed.brid.gy/r/https://jasm1nii.xyz/#update-2023-08-13T15:47:34.499697+00:00",
  "actor": "https://fed.brid.gy/jasm1nii.xyz",
  "@context": "https://www.w3.org/ns/activitystreams",
  "type": "Update",
  "object": {
    "id": "https://fed.brid.gy/jasm1nii.xyz",`
  **`"summary": "\ud83d\udccd IDN \ud83c\udfa8 illustrator & multimedia designer \ud83d\udc18 @jasm1nii@mas.to",`**
   ` "url": [
      "https://fed.brid.gy/r/acct:jasmine@jasm1nii.xyz",
      "https://jasm1nii.xyz/"
    ],`

these are the details it's supposed to show:
![image](https://github.com/snarfed/bridgy-fed/assets/67263692/c8d90d07-197e-4eca-8302-b8bd1e1824d9)

**Comment by snarfed** [comment] 2023-08-14 05:08
Ah, you mean the `🐘 @jasm1nii@mas.to` at the end of `summary`? Yup, I'm not seeing that on https://mas.to/@jasmine@jasm1nii.xyz yet either. BF delivered it to `https://mas.to/inbox` in the `Update` below at 8/14 03:12:43 UTC. We've seen profile updates occasionally be flaky before, not sure why, maybe caching, we might be seeing that again here. 😐 

```json
{
  "id": "https://fed.brid.gy/r/https://jasm1nii.xyz/#update-2023-08-14T03:12:42.600872+00:00",
  "actor": "https://fed.brid.gy/jasm1nii.xyz",
  "@context": "https://www.w3.org/ns/activitystreams",
  "type": "Update",
  "object": {
    "id": "https://fed.brid.gy/jasm1nii.xyz",
    "summary": "\ud83d\udccd IDN \ud83c\udfa8 illustrator & multimedia designer \ud83d\udc18 @jasm1nii@mas.to",
    "url": [
      "https://fed.brid.gy/r/acct:jasmine@jasm1nii.xyz",
      "https://jasm1nii.xyz/"
    ],
    "image": {
      "url": "https://jasm1nii.xyz/assets/media/main/07042023 me.png",
      "type": "Image",
      "name": "a self portrait of the author wearing a hijab, glasses, jewelry, and a collared blouse; drawn against a pink background"
    },
    "updated": "2023-08-14T03:12:42.600838+00:00",
    "type": "Person",
    "attachment": [
      {
        "type": "PropertyValue",
        "name": "Web site",
        "value": "<a rel=\"me\" href=\"https://jasm1nii.xyz/\"><span class=\"invisible\">https://</span>jasm1nii.xyz<span class=\"invisible\">/</span></a>"
      },
      {
        "url": "https://jasm1nii.xyz/assets/media/main/07042023 me.png",
        "type": "Image",
        "name": "a self portrait of the author wearing a hijab, glasses, jewelry, and a collared blouse; drawn against a pink background"
      }
    ],
    "icon": {
      "url": "https://jasm1nii.xyz/assets/media/main/07042023 me.png",
      "type": "Image",
      "name": "a self portrait of the author wearing a hijab, glasses, jewelry, and a collared blouse; drawn against a pink background"
    },
    "preferredUsername": "jasm1nii.xyz",
    "publicKey": {
      "id": "https://fed.brid.gy/jasm1nii.xyz",
      "owner": "https://fed.brid.gy/jasm1nii.xyz",
      "publicKeyPem": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnyFvknXJvPHPEb2KWN32\n3H6ynKZQflXTVWrzRL845LHHhQLYBE++lTFdauAgB0HLs7rBwtyQQQ8Ka2U0bwmU\ndT/l87ZFi/y6JgskPWhzwTSRFpEwSvR1fJQqTuWnjqS0fkCpOA1JjnHaPjVJOn0+\nTVBzupItI79YctLY/yo8IGPRD1stzNfaD1vzDY5Q57JnZOYtuK/MsZ3zdbnlUpkq\nnQih9JMNdA1OJPx5goeYbRhs+ubWSoBGb1zAOkoeRo+KT2iGuwFYzquuduhc6Ez4\nBPNeH9F+zIxc9FYYtgwBhC+sMDzS/VZQJ1MEWlg9l+rHSzG8rcmUFbd59PY2VecL\nZwIDAQAB\n-----END PUBLIC KEY-----"
    },
    "@context": [
      "https://w3id.org/security/v1"
    ]
  },
  "to": [
    "https://www.w3.org/ns/activitystreams#Public"
  ]
}
```

**Comment by silverpill** [comment] 2023-08-19 16:24
@snarfed I think I have a similar problem. My server rejects activity because the object of `Update` is not a valid actor object, as it doesn't contain `inbox` and `outbox` properties. Probably Mastodon rejects this activity for the same reason.

**Comment by snarfed** [comment] 2023-08-19 17:59
Oh interesting, good point! Looks like you're right, AP has those two additional properties as MUSTs: https://www.w3.org/TR/activitypub/#actor-objects

We've actually been seeing profile updates generally work on Mastodon instances they're delivered to, so that may not be the root cause here, but it sounds like it is with your server. Easy fix on my end, thanks for the nudge, will do.

**Comment by snarfed** [comment] 2023-08-19 22:23
Should be fixed now! Feel free to retry.

**Comment by silverpill** [comment] 2023-08-20 12:07
Thank you!

If I'll see a failing `Update` again I'll let you know.

**Comment by jasm1nii** [comment] 2023-08-24 00:55
just chiming in to say that my profile finally updated - i'm not sure if this was the exact fix, but i reattached the `h-card` class to a `div` element, instead of a semantic `section` element like before. both formats passed indiewebifyme's h-card validator, but i guess bridgy only picks up the former?

**Comment by snarfed** [comment] 2023-08-24 02:19
Glad it worked! No, it's not the HTML elements. Bridgy picked up your h-card ok before, you can see that [the AS2 object it sent before](https://github.com/snarfed/bridgy-fed/issues/614#issuecomment-1676686441) had all of your h-card's contents. The diff of that one vs the one it sent yesterday is below, it has a couple small changes but nothing really different structurally.

```patch
26a34,38
>         "url": "https://jasm1nii.xyz/assets/media/main/la-creatura.png",
>         "type": "Image",
>         "name": "an ASCII drawing of the autism creatue meme"
>       },
>       {
29c41
<         "name": "a self portrait of the author wearing a hijab, glasses, jewelry, and a collared blouse; drawn against a pink background"
--
>         "name": "a self portrait of the webmaster"
35c47
<       "name": "a self portrait of the author wearing a hijab, glasses, jewelry, and a collared blouse; drawn against a pink background"
--
>       "name": "a self portrait of the webmaster"
36a49,50
>     "inbox": "https://fed.brid.gy/jasm1nii.xyz/inbox",
>     "outbox": "https://fed.brid.gy/jasm1nii.xyz/outbox",
```

My guess is this is either the same flakiness and delays we've seen with Mastodon profile updates before, or _maybe_ the inbox/outbox fix in https://github.com/snarfed/bridgy-fed/issues/614#issuecomment-1685075587 .

Regardless, glad it's fixed!

**Closed by snarfed** 2023-08-24 02:19 UTC
