### ISSUE TITLE
AT -> AP: Posts marked as suggestive by BlueSky Moderation Service don't get CW'd

### ISSUE THREAD

**Issue by aspen4545** [snarfed/bridgy-fed#1443] opened 2024-10-30 23:19 UTC
When a post is marked as sensitive content by the BlueSky Moderation Service (i.e. not self-applied), the bridged AP post does not also get marked as sensitive content, which makes them difficult to boost. 

This is referring to posts labeled like this (Due to the nature of this I don't know if it's appropriate/allowed to post links to examples here...):
![image](https://github.com/user-attachments/assets/66de5669-c4dc-4439-bbf3-27b456321abb)

Since AP allows for edits to add content warnings, is this possible to listen for/apply to bridged posts?

**Comment by Tamschi** [comment] 2024-10-30 23:37
This is a duplicate of #971.

**Closed by Tamschi** 2024-10-30 23:37 UTC
Labels: see other

**Comment by aspen4545** [comment] 2024-10-30 23:39
My bad, tried to search and browse issues first but didn't find that one. Thank you!

**Comment by Tamschi** [comment] 2024-10-30 23:42
No issue, it took me two tries to look it up just now too.
It should be easier to find now since (I think) you used all the relevant keywords at once.
