### ISSUE TITLE
My reply posts (Fedi to Bsky) show with something deleted

### ISSUE THREAD

**Issue by emsquarial** [snarfed/bridgy-fed#1575] opened 2024-11-30 20:07 UTC
Bluesky users have pointed out that my replies from Mastodon show something deleted. There isn't anything extra below my posts and the info icon isn't clickable on Bluesky so wondering if this is some kind of bridge issue?
PS: This only occurs on replies to Bsky accounts.
Kind regards
![Bskyeleted](https://github.com/user-attachments/assets/c0d1ebdd-6770-415c-b821-935b3dc6483d)

**Comment by snarfed** [comment] 2024-11-30 22:43
Oops, yes! Looks like this is a bug caused by #1411. Thanks for reporting! Will fix.

**Comment by emsquarial** [comment] 2024-12-01 14:31
> Oops, yes! Looks like this is a bug caused by #1411. Thanks for reporting! Will fix.

Many thanks. Always appreciate the time and effort you put into this. Best wishes.

**Comment by snarfed** [comment] 2024-12-01 16:24
Should be fixed as of last night, thanks again for reporting!

**Closed** 2024-12-01 16:24 UTC
Labels: now, bug
