### ISSUE TITLE
Some posts are not being bridged AP->Bsky, occasionally boosts/likes don't bridge bsky->AP

### ISSUE THREAD

**Issue by TomCasavant** [snarfed/bridgy-fed#1037] opened 2024-05-09 15:35 UTC
I don't know what the issue is, but I figured you'd probably want the data just in case it relates to any sort of specific issue you're seeing.
AP ->Bsky:
https://tomkahe.com/@tom/112411725858622051 -> Text only

https://tomkahe.com/@tom/112411643572243541 -> text only

https://tomkahe.com/@tom/112408526039829185 -> text only

https://tomkahe.com/@tom/112407978401605379 -> Media Only, Most recent successful bridge (didn't have the media but that's expected), https://bsky.app/profile/tom.tomkahe.com.ap.brid.gy/post/3krz7j6iu4rc2

Bsky->AP:
https://tomkahe.com/@tom/112406411259235899 - Should be boosted by my test account @globetrotters.bsky.social@bsky.brid.gy but isn't there

( For reference https://tomkahe.com/@tom/112403069808343286 did receive the boost and was posted in a time frame between the others)

https://tomkahe.com/@tom/112402629834933471 -> Boost/like did not show up

Not a big issue, just figured you'd want to have the information

**Comment by snarfed** [comment] 2024-05-09 15:44
Thanks! I'm about to roll out #978, I'm hopeful that will fix most/all instances of missing Bluesky activity like these.

**Comment by snarfed** [comment] 2024-05-09 23:02
...and likewise, I think I know the root cause(s) of the missing AP => Bluesky activity. I'm going to track that in #1038.

Closing this in favor of tracking in those two issues. Thank you again!

**Closed by snarfed** 2024-05-09 23:02 UTC
