### ISSUE TITLE
Jobs from bsky.brid.gy got delayed on some fediverse instances, especially Misskey-based

### ISSUE THREAD

**Issue by ufalsalman** [snarfed/bridgy-fed#1657] opened 2024-12-28 05:01 UTC
I have a fedi account as my main at [@ufal@misskey.id](https://misskey.id/@ufal) and a Bluesky account at [@ufal.my.id](https://bsky.app/profile/ufal.my.id). I have been bridging for three months now.

But lately I never got my own posts from my Bluesky account on my fedi timeline in the last couple of days, as seen on the screenshot where the right one is my posts on Bluesky, the left one is my Bluesky account shows on misskey.id but not showing my own posts, only some reposts I have done in the last couple of days, and the middle on the view from mastodon.social, which shows my posts. I mark he posts some red lines to highlight which posts that shows from Bluesky to mastodon.social.

I don't have other Mastodon accounts that already in mutual with my Bluesky account so I can't check if this is the issue on Bridgy Fed or Misskey. But when I checked on sakurajima.social, which is Sharkey-based, also got the same issue, and the last post shown is my own post from a week ago.

One more thing, some posts that are reposted by some Bluesky users I already followed usually will show themselves on misskey.id. Which is weird too. And this isn't a big problem on Bluesky, my fedi account still able to bridge over there and shows the posts immediately.

![image](https://github.com/user-attachments/assets/6a213fb4-147a-4c37-8fb1-e26567e2bef5)
![image](https://github.com/user-attachments/assets/d470084a-d15b-4d3c-a4cd-e9d908bdbab6)

I contacted the [admin](https://misskey.id/@sandycorzeta), and he said that the inbox always be delayed (with the first image attached below) and shows this error (the second image).

![mw8llwg](https://github.com/user-attachments/assets/7cb6e278-8c2b-4e45-b701-64da960142b1)
![kQPWx9g](https://github.com/user-attachments/assets/cc13347b-35a4-40e1-9a56-d9144f9ef787)

I am speaking as a user, not an admin of misskey.id. I just want to get this thing through and help people on my server if there's anything I can do.

**Comment by saschanaz** [comment] 2024-12-28 22:34
Dupe of #1570 ?

**Comment by snarfed** [comment] 2024-12-29 00:20
Agreed, based on the error message in that screenshot, this looks like https://github.com/snarfed/bridgy-fed/issues/1570#issuecomment-2558187705.

**Comment by snarfed** [comment] 2024-12-29 00:20
Duplicate of #1570

**Closed by snarfed** 2024-12-29 00:20 UTC
