### ISSUE TITLE
[AT -> AP] Activitypub “onboarding”

### ISSUE THREAD

**Issue by FurblandChannel** [snarfed/bridgy-fed#1528] opened 2024-11-20 20:44 UTC
Upon interacting with an account bridged from AT to AP, if it is the first time a user has done this, the bot might want to send a DM explaining you will need to follow the bot for the interaction to transfer over.

**Comment by snarfed** [comment] 2024-11-20 20:57
Yes! We already do this now, #1205, but not consistently, and we may do it even less in the future as a result of #1149. I expect to make more UX compromises like this soon to help scale and keep costs under control, at least as long as this is just one person's side project 😁 https://snarfed.org/2024-11-01_53932

**Comment by imakiro** [comment] 2024-11-21 18:26
Is there a way that people could help you run stuff and limit costs to keep quality of onboarding high?
The outbound message sender maybe ?

**Comment by snarfed** [comment] 2024-11-21 19:42
We're working on setting up an org and taking donations! I got some good responses to https://snarfed.org/2024-11-01_53932

**Comment by snarfed** [comment] 2024-11-22 01:22
Duplicate of #1205

**Closed by snarfed** 2024-11-22 01:22 UTC
