### ISSUE TITLE
Fediverse accounts stopped being bridged to Bluesky

### ISSUE THREAD

**Issue by DoktorZjivago** [snarfed/bridgy-fed#1038] opened 2024-05-09 22:09 UTC
Lots of fediverse accounts opted in about a week ago. However, since about 3-4 days, nothing gets through to bluesky. The mirrored accounts are still there, but no posts, likes, comments, reposts or anything comes up on bluesky. Seen this on several accounts. However, accounts that opted in recently, today and yesterday, seem to bridge just fine.

**Comment by DoktorZjivago** [comment] 2024-05-09 22:24
For context, here are a few fediverse accounts that opted in a week ago that doesn't get bridged anymore:

https://mastodonsweden.se/@doktorzjivago

https://mastodon.nu/@LeoR1010

https://mementomori.social/@rolle

And here are some fediverse accounts that opted in more recently, that still get bridged:

https://robertparker.se/@robertparker

https://mastodonsweden.se/@Kricko

**Comment by snarfed** [comment] 2024-05-09 23:01
Thanks for the report, and for the examples! I _think_ I know what's going on here; I think it's related to some cases where we emit invalid ATProto records - #1015, #1016, #1007 - and the relay gets stuck on those repos and won't ingest new records for thenm. I expect this is the same root cause underlying the AP => Bluesky part of #1037.

This will take some debugging and work to resolve, even with @mackuba's hugely helpful investigations so far, but it's very doable. High on my list of priorities..

**Comment by snarfed** [comment] 2024-05-14 05:09
Fixing `getRepo` seemed to do the trick here! I'm seeing the relay use that to re-index more and more of these accounts.  As examples, https://bsky.app/profile/doktorzjivago.mastodonsweden.se.ap.brid.gy and https://bsky.app/profile/leor1010.mastodon.nu.ap.brid.gy are now unstuck and bridging again.

https://bsky.app/profile/rolle.mementomori.social.ap.brid.gy isn't, though, and I'm not sure why. All of his recent posts have hashtags, and it's possible we're generating invalid ATProto records for those, but unlikely. Hrm.

**Comment by DoktorZjivago** [comment] 2024-05-14 11:21
Yes I saw it worked again, very cool!

**Comment by snarfed** [comment] 2024-05-15 17:37
Tentatively closing. Feel free to reopen or follow up if you see more examples, I can check if the relay hasn't re-indexed them yet.

**Closed** 2024-05-16 01:52 UTC
Labels: now
