### ISSUE TITLE
Missing inbox property when fetching with handle name

### ISSUE THREAD

**Issue by saschanaz** [snarfed/bridgy-fed#1653] opened 2024-12-26 15:44 UTC
```
> curl -H "Accept: application/activity+json" https://bsky.brid.gy/r/https://bsky.app/profile/bsky.app
{
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    {
      "discoverable": "http://joinmastodon.org/ns#discoverable",
      "indexable": "http://joinmastodon.org/ns#indexable"
    },
    {
      "PropertyValue": "schema:PropertyValue",
      "schema": "http://schema.org#"
    }
  ],
  "attachment": [
    {
      "name": "Link",
      "type": "PropertyValue",
      "value": "<a rel=\"me\" href=\"https://bsky.app/profile/bsky.app\"><span class=\"invisible\">https://</span>bsky.app/profile/bsky.app</a>"
    },
    {
      "name": "Link",
      "type": "PropertyValue",
      "value": "<a rel=\"me\" href=\"https://bsky.app\"><span class=\"invisible\">https://</span>bsky.app</a>"
    },
    {
      "type": "Image",
      "url": "https://puffball.us-east.host.bsky.network/xrpc/com.atproto.sync.getBlob?did=did:plc:z72i7hdynmk6r22z27h6tvur&cid=bafkreichzyovokfzmymz36p5jibbjrhsur6n7hjnzxrpbt5jaydp2szvna"
    },
    {
      "type": "Image",
      "url": "https://puffball.us-east.host.bsky.network/xrpc/com.atproto.sync.getBlob?did=did:plc:z72i7hdynmk6r22z27h6tvur&cid=bafkreihagr2cmvl2jt4mgx3sppwe2it3fwolkrbtjrhcnwjk4jdijhsoze"
    }
  ],
  "discoverable": true,
  "icon": {
    "type": "Image",
    "url": "https://puffball.us-east.host.bsky.network/xrpc/com.atproto.sync.getBlob?did=did:plc:z72i7hdynmk6r22z27h6tvur&cid=bafkreihagr2cmvl2jt4mgx3sppwe2it3fwolkrbtjrhcnwjk4jdijhsoze"
  },
  "id": "https://bsky.brid.gy/ap/did:plc:z72i7hdynmk6r22z27h6tvur",
  "image": [
    {
      "type": "Image",
      "url": "https://puffball.us-east.host.bsky.network/xrpc/com.atproto.sync.getBlob?did=did:plc:z72i7hdynmk6r22z27h6tvur&cid=bafkreichzyovokfzmymz36p5jibbjrhsur6n7hjnzxrpbt5jaydp2szvna"
    },
    {
      "type": "Image",
      "url": "https://puffball.us-east.host.bsky.network/xrpc/com.atproto.sync.getBlob?did=did:plc:z72i7hdynmk6r22z27h6tvur&cid=bafkreihagr2cmvl2jt4mgx3sppwe2it3fwolkrbtjrhcnwjk4jdijhsoze"
    }
  ],
  "indexable": true,
  "name": "Bluesky",
  "preferredUsername": "bsky.app",
  "summary": "official Bluesky account (check username\ud83d\udc46)\n\nBugs, feature requests, feedback: support@bsky.app",
  "to": [
    "https://www.w3.org/ns/activitystreams#Public"
  ],
  "type": "Person",
  "url": [
    "https://bsky.brid.gy/r/https://bsky.app/profile/bsky.app",
    "https://bsky.brid.gy/r/https://bsky.app/"
  ]
}
```

It still works as implementations like Misskey will fetch again from the id property value, but it's still confusing.

**Comment by snarfed** [comment] 2024-12-26 16:12
Thanks for the info! Handling in #1654.

**Comment by snarfed** [comment] 2024-12-26 16:12
Duplicate of #1654

**Closed by snarfed** 2024-12-26 16:12 UTC
