### ISSUE TITLE
allow contorl of other end bridged account.

### ISSUE THREAD

**Issue by alien-sunset** [snarfed/bridgy-fed#1439] opened 2024-10-29 20:36 UTC
i'm bridging my mastodon to bluesky, but have no control over the bluesky end, cannot log in as it etc.

this is problematic beaus say, maybe, sometimes i may make a post that later needs to be deleted, and I cannot do it, so that post still exists on bluesky because i do not have control over that account, although it it posting MY content.
this seems rather messy and open to legal issues amongst other things.

**Comment by Tamschi** [comment] 2024-10-29 21:05
The bridge bridges deletions too, so it **should** always delete the bridged post along with the original.

If a post doesn't get deleted, that may be due to https://github.com/snarfed/arroba/issues/34 which currently makes the outbound firehose unreliable. In those cases, I think @snarfed should be able to reissue the deletion manually if necessary.

**Comment by michael-patchwork** [comment] 2024-10-30 10:13
Hi @Tamschi @snarfed now we have domains as handles on bridged accounts, making them closer to first class citizens (which is fantastic and just what we needed) is it possible to go the next step and issue a password to the bridged account so the user can log on? There could be things the user wants to do on Bluesky which can’t be done through the bridge. Could that be possible in future?

**Comment by Tamschi** [comment] 2024-10-30 11:06
[Bridged accounts won't be able to be used manually](https://github.com/snarfed/bridgy-fed/issues/1137#issuecomment-2439202355), no.
(The PDS used by Bridgy Fed is also somewhat limited I believe, so it's not like a switch that could be flipped.)

To interact fully with ATProto, you'll need a proper general-purpose PDS, like the ones where Bluesky creates its native accounts.
At some point, it should also be possible to migrate a bridge account into a native one, but this will disconnect the Bridge. (#1137)

Specifically for websites, you could also use [Bridgy](https://brid.gy/) (not "Fed"!) to connect your site to an existing native account.
That project does not bridge between social media accounts, though, so to use both sites at once, a crossposter may be more useful than a bridge.

---

All that said, what specifically would you like to do?
Specific actions may be supported remotely eventually, like blocking users that aren't bridged. (#1406)

**Comment by alien-sunset** [comment] 2024-10-30 15:21
make bluesky specific posts for one....
or delete masto specific posts to prevent confusion.

I have a bot that i'm bridging and just found out that it's instance is closing down, i'd like to make an announcement about that fact and my plans on moving.

but none of that is applicable to bluesky, there the bot is just going to die at that address (and hopefully be deleted once i end the bridge?)
and i will need to create a new mirror, perhaps with brid.gy or perhaps with a new provider that allows more controll.

**Comment by snarfed** [comment] 2024-10-30 15:29
Aha. Definitely makes sense! Sounds like you'd be interested in #831? We don't have that yet, but maybe someday!

**Comment by snarfed** [comment] 2024-10-30 15:30
From that issue: 

> Until we have this, if you're on the fediverse, one way to bridge only some of your posts is to use public vs unlisted. Bridgy Fed only bridges fully public posts; it ignores unlisted, followers-only, and other non-public posts.

**Comment by alien-sunset** [comment] 2024-10-30 17:55
> From that issue:
> 
> > Until we have this, if you're on the fediverse, one way to bridge only some of your posts is to use public vs unlisted. Bridgy Fed only bridges fully public posts; it ignores unlisted, followers-only, and other non-public posts.

this still doesn't address teh need to occasionally make bluesky specific posts.

**Comment by snarfed** [comment] 2024-10-30 18:14
> this still doesn't address teh need to occasionally make bluesky specific posts.

Very true!

I've documented that [I don't plan to build out support for people logging into bridged accounts and using them like normal accounts](https://fed.brid.gy/docs#use-like-normal). It would be way too much work, and too difficult and error prone.

However, per-post bridging is a great feature request! Let's track that in #831.

Tentatively closing, but feel free to reopen if you want.

Duplicate of #831

**Closed by snarfed** 2024-10-30 18:14 UTC

**Comment by michael-patchwork** [comment] 2024-10-30 18:20
Thanks! Understood. Anyone wanting to do that can open an account and cross post to it, rather than using the bridge.

**Comment by Tamschi** [comment] 2024-10-30 18:40
> but none of that is applicable to bluesky, there the bot is just going to die at that address (and hopefully be deleted once i end the bridge?)
> and i will need to create a new mirror, perhaps with brid.gy or perhaps with a new provider that allows more controll.

On that note, Bridgy Fed could (but doesn't yet!) track ActivityPub migrations by changing the ATProto handle of the existing bridge account, thereby preserving Bluesky followers. More on that here: https://github.com/snarfed/bridgy-fed/issues/330#issuecomment-2408856682

I'll file that as separate issue to at least keep track of it.
