### ISSUE TITLE
Possible addition of instruction on bridged accounts to follow @ap.brid.gy

### ISSUE THREAD

**Issue by ken-oh** [snarfed/bridgy-fed#1517] opened 2024-11-19 12:51 UTC
Even though I gave clear instructions, I've got a 1/5 rate of follow through from friends on Bluesky in following @ap.brid.gy after following my bridged account. I wonder if changing 
[bridged from mstdn.social/@kenoh on the fediverse by fed.brid.gy ]

to something like

[bridged from mstdn.social/@kenoh on the fediverse by fed.brid.gy, to allow this account to follow you back, please follow @ap.brid.gy ]

would increase that rate.

**Comment by snarfed** [comment] 2024-11-20 00:15
It's definitely an interesting idea! We've discussed it a bit already on https://github.com/snarfed/bridgy-fed/discussions/1347 , feel free to jump in there.

**Comment by snarfed** [comment] 2024-11-22 01:26
Duplicate of #1347

**Closed by snarfed** 2024-11-22 01:26 UTC
