### ISSUE TITLE
Mentioning a BSky bridged account on Mastodon links to a raw JSON file

### ISSUE THREAD

**Issue by edent** [snarfed/bridgy-fed#1441] opened 2024-10-30 09:39 UTC
I've linked  https://bsky.app/profile/openbenches.org to `@openbenches.org@bsky.brid.gy`

If I [mention the new account on Mastodon](https://mastodon.social/@Edent/113395640323433214), some users report that clicking on it results in being served a JSON file:

* https://swiss.social/@darkcisum/113395660031030572
* https://hachyderm.io/@http_error_418/113395644143499459

The raw HTML of my mention shows:

```html
<a href="https://bsky.brid.gy/ap/did:plc:6w5rx6ik4qvl2jfw6orcnpup" class="u-url mention">
   @<span>openbenches.org</span>
</a>
```

Some apps (Fedilab) support clicking on that and showing the account properly. Others (Tusky) don't.  
If I click on the link from the website I use, it works. If I click on a link from a different Mastodon instance, I get the JSON.

**Comment by snarfed** [comment] 2024-10-30 14:40
Yes! Thanks @jfietkau, moving to bridgy-fed. And thanks for filing @edent! This is a weird one, we've seen it occasionally on and off for a long time, but I still don't fully understand it. I'm going to merge this into #1009 (and maybe merge #1429 in there too) and expand that issue to include Mastodon.

**Comment by snarfed** [comment] 2024-10-30 14:40
Duplicate of #1009

**Closed by snarfed** 2024-10-30 14:40 UTC
