### ISSUE TITLE
[feature] respect (or at least acknowledge) fediseer data

### ISSUE THREAD

**Issue by FurblandChannel** [snarfed/bridgy-fed#1426] opened 2024-10-26 00:26 UTC
https://fediseer.com/ is an open project to track abusive or spammy Fediverse instances. checking accounts and instances against data from this service may help reduce spam traffic and undesirable accounts being bridged.

**Comment by snarfed** [comment] 2024-10-26 03:18
Yes! We currently use [Seirdy's Fedinuke](https://seirdy.one/pb/FediNuke.txt), and there are many more, not just Fediseer but also [Seirdy's other blocklists](https://seirdy.one/posts/2023/05/02/fediverse-blocklists/), [Oliphant's](https://writer.oliphant.social/oliphant/the-oliphant-social-blocklist), [Threads's](https://www.threads.net/moderated_servers), [IFTAS DNI](https://connect.iftas.org/library/iftas-documentation/iftas-dni-list/), [IFTAS FediCheck](https://connect.iftas.org/library/iftas-documentation/fedicheck/) and more. We're tracking supporting more of them in #1008.

**Comment by snarfed** [comment] 2024-10-26 03:19
Tentatively closing as duplicate of #1008

**Closed by snarfed** 2024-10-26 03:19 UTC

**Comment by FurblandChannel** [comment] 2024-10-26 04:07
Got it, I’ll follow that one.
