### ISSUE TITLE
Glitches After DNS Verification on BlueSKy

### ISSUE THREAD

**Issue by Dice-Carver** [snarfed/bridgy-fed#1598] opened 2024-12-05 09:14 UTC
I followed Bridgy Fed when my handle on BlueSky was @elikpwilliam.bsky.social and this successfully generated the profile here: 
https://mastodon.social/@elikpwilliam.bsky.social@bsky.brid.gy

However, I have since verified and changed my BlueSky handle to @elikpwilliam.com

The automated Mastodon account has not updated my handle accordingly. The result is that if you click the link for my BlueSky account (https://bsky.app/profile/elikpwilliam.bsky.social) on my automated Mastodon account, you get a 404. 

Is there someway to update the handle of my automated Mastodon profile to reflect my new BlueSky handle?

**Comment by snarfed** [comment] 2024-12-05 13:52
Argh, sorry we don't support this well yet. Details in #1074.

**Comment by snarfed** [comment] 2024-12-05 13:52
Duplicate of #1074

**Closed by snarfed** 2024-12-05 13:52 UTC
