### ISSUE TITLE
Potential solution to OAuth woes

### ISSUE THREAD

**Issue by FurblandChannel** [snarfed/bridgy-fed#1583] opened 2024-12-02 07:53 UTC
I’ve heard people here mention how we need to verify accounts on the fediverse for various things time and time again. Bsky has a standard way of doing this, but most fedi platforms do not. I believe I have come up with a solution. It’s a bit janky, but it gets the job done.

- user visits page on fed.brid.gy and enters their handle
- page supplies them with code and prompts user to check DMs
- bot DMs user unique link which expires after a certain time period
- user then has to enter the code from the other page into this one to verify their account

having to enter a code from the page that initiated the verification in the page at the unique link ensures an instance admin can’t just snoop around in people’s DMs and authenticate as them

**Comment by FurblandChannel** [comment] 2024-12-03 08:35
> Is there a specific use case you think BF needs this for that can't be solved by the user just DMing the bot account directly though?

Not currently, but if we were to implement, say, that web dashboard for managing bridged accounts someone proposed, we'd need a way to authenticate for that.

**Comment by snarfed** [comment] 2024-12-03 15:55
True! Good point, thanks. I'm going to merge this into that issue, #1421.

**Comment by snarfed** [comment] 2024-12-03 15:56
Duplicate of #1421

**Closed by snarfed** 2024-12-03 15:56 UTC
