### ISSUE TITLE
AP reply to unbridged accounts/posts is bridged to Bluesky

### ISSUE THREAD

**Issue by TomCasavant** [snarfed/bridgy-fed#1166] opened 2024-07-06 00:36 UTC
https://bsky.app/profile/tom.tomkahe.com.ap.brid.gy/post/3kwl2m5dvwcz2

https://tomkahe.com/@tom/112736397018480884

*possibly* because the reply is too long so it's skipping over something when it truncates?

I see the same thing in these
https://bsky.app/profile/laurenshof.indieweb.social.ap.brid.gy/post/3kwjidaqxh2d2 (same thread as above)

https://bsky.app/profile/laurenshof.indieweb.social.ap.brid.gy/post/3kwjidaqxh2d2
https://bsky.app/profile/laurenshof.indieweb.social.ap.brid.gy/post/3kwjirhhhz7d2

**Comment by snarfed** [comment] 2024-07-06 17:59
Thanks for reporting! Looks like #1047 took us from too conservative to too liberal. Will fix.

**Comment by snarfed** [comment] 2024-07-07 23:54
May be a simple fix for a dumb bug, I'm guessing the answer is to start the conditional here with `if is_reply and ...`:

https://github.com/snarfed/bridgy-fed/blob/dd21c6c30194e0a7d2b3c6e233d00d3fa2676c1c/protocol.py#L1270-L1274

Need to confirm that that's actually the cause first.

**Comment by snarfed** [comment] 2024-07-10 02:33
714c317dd473489b21ce38ea2117a960a791c4b7 is a beast, but it's looking promising. 🤞 Example reply that didn't get bridged because its in-reply-to post wasn't bridged: https://indieweb.social/@snarfed/112759737604412729

**Comment by snarfed** [comment] 2024-07-10 02:35
Tentatively closing. Thanks again for reporting @TomCasavant, please reopen if you see any more of these!

**Closed by snarfed** 2024-07-10 02:35 UTC
Labels: now
