### ISSUE TITLE
Invitation DMs Aren't Received

### ISSUE THREAD

**Issue by Shanesan** [snarfed/bridgy-fed#1592] opened 2024-12-03 04:27 UTC
Sent an invitation to a user through Brid.gy DMs on Mastodon for someone on Bluesky at 12:56 PM EST 12/2, they did not recieve it by 11:01 PM.

Message sent to Brid.gy was:

> @bsky.brid.gy@bsky.brid.gy USERNAME.bsky.social

With the response

> Got it! We'll send PROPERLY IDENTIFIED USER a message and say that you hope they'll enable the bridge. Fingers crossed!

Sending it again says that Bridgy Fed already sent a DM.

Is there an issue with the DM system?

**Comment by snarfed** [comment] 2024-12-03 05:13
Hmm, sorry for the trouble! No issue that I know of. Does https://fed.brid.gy/docs#troubleshooting help?

**Comment by Shanesan** [comment] 2024-12-03 05:40
Hi @snarfed, I checked the troubleshooting section one by one, and nothing there seems to be an issue. Bridgy and my account seem to be in good graces. 

Is there a way I can link you to the DM’s that I’m having with Bridgy to see if those commands went through? 

I don’t see anything, say, on my user page that my BSky User DMed those users. I’m unsure how that process works. 

It’s also weird, because Bridgy said that the message was sent, which sounds pretty out of my hands when the user didn’t receive it.

**Comment by Shanesan** [comment] 2024-12-03 05:41
Just to add, is there an “age” that the Bluesky account has to be to receive DM‘s from Bridgy?

**Comment by Tamschi** [comment] 2024-12-03 09:25
If I remember correctly, the invite DMs are sent by `@ap.brid.gy` rather than your bridge account, so by default they will only be seen once the Bluesky user already follows that account.

It's definitely not ideal. On the other hand, if we DM from a bridge user then that opens a conversation that could be replied to, where we'd need to have an auto-response that Chat isn't bridged (and *if I remember correctly*, the Chat API there is poll-only for seeing new messages, so it would scale very badly to acting as multiple accounts).

**Comment by Shanesan** [comment] 2024-12-03 16:15
Awesome, thanks for that info @snarfed; it wasn't obvious from the troubleshooting list!

Once that Bsky account is two weeks old, do I send them another invite or how do I rescind the old one?

**Comment by snarfed** [comment] 2024-12-03 16:25
There isn't a way to do either right now, sorry. Feel free to reach out them another way if you want!

**Comment by snarfed** [comment] 2024-12-03 22:53
Duplicate of #758

**Closed by snarfed** 2024-12-03 22:53 UTC
