### ISSUE TITLE
Error 401 when trying to publish

### ISSUE THREAD

**Issue by rretsiem** [snarfed/bridgy-fed#70] opened 2020-10-28 22:00 UTC
Is there an issue with publishing posts to Mastodon (mastodon.social) instances? Since today (havent published to bridgy-fed for about 3 weeks) I get an HTTP 401 - not authorized error.

`I 2020-10-28 21:25:22.029036 Verification failed for [renem.net](http://renem.net/)@[renem.net](http://renem.net/) https://fed.brid.gy/renem.net
E 2020-10-28 21:25:22.029431 https://mastodon.social/inbox 
Traceback (most recent call last): 
  File "/srv/oauth_dropins/webutil/[util.py](http://util.py/)", line 1480, in call
   resp.raise_for_status()
  File "/env/lib/python3.7/site-packages/requests/[models.py](http://models.py/)", line 941, in raise_for_status
   raise HTTPError(http_error_msg, response=self)
[requests.exceptions.HTTPError](http://requests.exceptions.httperror/): 401 Client Error: Unauthorized for url: https://mastodon.social/inbox
E 2020-10-28 21:25:22.107845 No targets or followers. Ignoring.
`

See the log here: https://fed.brid.gy/log?key=https%3A%2F%2Frenem.net%2Fphotos%2F2020-10-28-baguette-bateau%2F+https%3A%2F%2Fmastodon.social%2Finbox&amp;start_time=1603920322
Looking at the latest logs, it seems I’m not alone with this issue? Any tips/hints?

(Originally published at: https://renem.net/notes/github/2020-10-28-1/)

**Comment by snarfed** [comment] 2020-10-28 23:49
hey, sorry for the trouble! this is a known breakage due to changes in Mastodon 3.2.1 that we're still working through. details in https://github.com/snarfed/bridgy-fed/issues/68#issuecomment-714752553 . sadly we're still not sure of the exact root cause, so i don't have an ETA on a fix yet.

**Comment by rretsiem** [comment] 2020-10-29 08:36
Thanks for the heads up. Sorry that I opened it and didn’t search for the issues first. From the title lookup on the issue list, it wasn’t clear to me that it is the same issue. However, any glue why the (Originally published… ) link in the opening comment here, points to the Issue-Tracker on Github and not to my issue-note on my blog? The log on Brid.gy has both URLs in the list.

(Originally published at: https://github.com/snarfed/bridgy-fed/issues/70#issuecomment-718272394)

**Comment by snarfed** [comment] 2020-10-29 17:08
hah, yes! looking at the [bridgy publish log](https://brid.gy/log?start_time=1603922429&key=agdicmlkLWd5clMLEg1QdWJsaXNoZWRQYWdlIixodHRwczovL3JlbmVtLm5ldC9ub3Rlcy9naXRodWIvMjAyMC0xMC0yOC0xLwwLEgdQdWJsaXNoGICAsM-GqoEJDA), your original post https://renem.net/notes/github/2020-10-28-1/ evidently has `u-url` on the link to https://github.com/snarfed/bridgy-fed/issues as well as the link to itself. i'm guessing that's unintentional. if you remove that `u-url`, the _Originally published at_ should work right.

**Comment by snarfed** [comment] 2020-11-17 17:16
tentatively closing. feel free to reopen!

**Closed by snarfed** 2020-11-17 17:16 UTC
