### ISSUE TITLE
Bluesky profile bridged to Mastodon is missing newlines in the profile description

### ISSUE THREAD

**Issue by mvdan** [snarfed/bridgy-fed#1556] opened 2024-11-26 08:34 UTC
My profile at https://bsky.app/profile/mvdan.cc has the description

> #cuelang #golang
> https://mvdan.cc
> London, UK

whereas the mirrored profile at https://fosstodon.org/@mvdan.cc@bsky.brid.gy seems to have the description

> #cuelang #golang https://mvdan.cc/ London, UK
> 
> [[bridged](https://fed.brid.gy/bsky/mvdan.cc) from [mvdan.cc](https://bsky.app/profile/mvdan.cc) on Bluesky by [Bridgy Fed](https://fed.brid.gy/)]

I can't see the description on https://fed.brid.gy/bsky/mvdan.cc so I can't tell for sure whether this is a bug in the mirroring/bridging or in the way Mastodon renders. However, I did just edit my original fosstodon profile with the same three lines, and it does render as expected with three lines: https://fosstodon.org/@mvdan

**Comment by mvdan** [comment] 2024-11-26 08:35
Thank you for all your hard work, by the way!

**Comment by snarfed** [comment] 2024-11-26 15:02
Thanks for the kind words! Looks like this is #990

**Comment by snarfed** [comment] 2024-11-29 16:26
Duplicate of #990

**Closed by snarfed** 2024-11-29 16:26 UTC
