### ISSUE TITLE
Not all posts from Bluesky user show up on Mastodon

### ISSUE THREAD

**Issue by beetleb** [snarfed/bridgy-fed#1626] opened 2024-12-15 02:10 UTC
I have a Mastodon account (@beetle_b@mastodon.xyz). It is mutually following Bridgy Fed for Bluesky (both ways).

A friend has a Bluesky account ([@jskharay.bsky.social](https://bsky.app/profile/did:plc:tfs6xtshxk33ihooqj7fr3j5)). He also is following the counterpart to bridge to Mastodon.

I believe he can see my public posts. But I don't think I can see his. He posted [something](https://bsky.app/profile/jskharay.bsky.social/post/3ldbxhtvris2y) publicly, but it doesn't show up on his counterpart in Mastodon: @jskharay.bsky.social@bsky.brid.gy

He posted it after we both had mutual relationships with the Bridgy Fed accounts (and were mutually following each other). 

I made a public toot with his handle, and he received it. He replied to it, and that one *does* show up on Mastodon.

So the experiments so far:

1. He (on Bluesky) can see my public toots (on Mastodon) - at least ones where I tag him.
2. He can reply to my toot from within Bluesky and I see it on Mastodon.
3. His general public post doesn't show up on Mastodon.

Any ideas how to debug this?

Thanks!

**Comment by snarfed** [comment] 2024-12-15 03:58
Hey, sorry for the trouble! Have you looked at https://fed.brid.gy/docs#troubleshooting ?

**Comment by beetleb** [comment] 2024-12-15 04:59
> Hey, sorry for the trouble! Have you looked at https://fed.brid.gy/docs#troubleshooting ?

Sorry - I should have mentioned that I had:

Originally I did not have a profile picture, so I unfollowed, added a picture, and followed (and Mastodon showed a "Mutual" relationship with the bridge). The posts in my issue all came *after* this, so I don't think a profile picture was the problem. 

My Mastodon account is from 2018. 

As you can see from his Bluesky profile, his comment that I linked to is fully public (I assume - I'm not a Bluesky user so I don't know the intricacies).

I'm assuming he doesn't have the "hide account in logged out view" setting enabled (as you and I can see his profile). 

My server's *About* page doesn't show it blocking the bridge. I assume if it did, then none of the posts would have been bridged.

My username is not weird.

**Comment by snarfed** [comment] 2024-12-15 05:54
Ah, they don't have any followers in the fediverse - see https://fed.brid.gy/bsky/jskharay.bsky.social - so we don't have anywhere to deliver their posts: https://fed.brid.gy/docs#:~:text=at%20least%20one%20follower

**Comment by snarfed** [comment] 2024-12-15 06:01
You can see it in the fediverse if you search for its bridged URL, https://bsky.brid.gy/r/https://bsky.app/profile/jskharay.bsky.social/post/3ldbxhtvris2y , on an instance where you're logged in.

**Comment by beetleb** [comment] 2024-12-15 06:59
OK - I'm confused: 

I thought I am a follower. See this screenshot:

![jas1](https://github.com/user-attachments/assets/98d8d8d3-b543-4c22-b9ad-b8cfedcd307d)

And here is how it shows up in my list of followers - note the bidirectional arrows:

![jas2](https://github.com/user-attachments/assets/7c85deb9-12b2-4c0c-b467-abeb5141f628)

So it's interesting the Bridgy Fed is not showing any followers.

**Comment by Tamschi** [comment] 2024-12-15 10:10
That seems like a follower desync somewhere in Bridgy Fed.

**Comment by Tamschi** [comment] 2024-12-15 10:15
I wonder if this is an interaction with un-bridging a Mastodon account or the account getting spam-filtered for not having a profile picture. Neither of those occurrences should remove them as a follower of another account in the database.

The spam filter also shouldn't affect follows of bridge users and maybe we should send an `Undo`.`Accept`.`Follow` in response to an `Undo`.`Follow` regarding a bridge account 🤔

**Comment by snarfed** [comment] 2024-12-15 16:07
> I wonder if this is an interaction with un-bridging a Mastodon account or the account getting spam-filtered for not having a profile picture.

Good point! Or being less than two weeks old. @beetleb do either of those apply to your fediverse account? If so, this is probably #1135.

**Comment by Tamschi** [comment] 2024-12-15 17:49
In that case, there's likely a distinct bug here of Bridgy Fed responding with an `Accept`.`Follow` too eagerly.

**Comment by beetleb** [comment] 2024-12-15 18:05
> > I wonder if this is an interaction with un-bridging a Mastodon account or the account getting spam-filtered for not having a profile picture.
> 
> Good point! Or being less than two weeks old. @beetleb do either of those apply to your fediverse account? If so, this is probably #1135.

As I said, when I initially followed the accounts (both the bridge itself and his bridged account), I did not have a profile picture. Then I saw the item in the Docs about needing a profile picture, and I added one - then I unfollowed both accounts and refollowed them. As you can see in my screenshot above, it is now showing mutual following with both accounts.

And yes, I always had a display name.

Let me know if there's anything you want me to try. Perhaps unfollow and refollow both again?

**Comment by beetleb** [comment] 2024-12-15 18:37
Also, are there any well known accounts on Bluesky with a Fediverse bridge that posts often, so I can experiment with their accounts? I don't want to keep bugging my friend to post :-)

**Comment by snarfed** [comment] 2024-12-15 19:09
Thanks for all the info here! Hmm, Bridgy Fed saw your latest unfollow, but didn't see a re-follow after that: https://fed.brid.gy/ap/@beetle_b@mastodon.xyz . Looking at our logs, we never got a second valid `Follow` activity follow after that `Undo` of the first follow. Not sure why mastodon.xyz didn't deliver one; maybe try again?

**Comment by beetleb** [comment] 2024-12-15 19:17
OK. I unfollowed and refollowed, and now it's showing the FOLLOW in your logs. Do I need to unfollow and refollow my friend in Bluesky as well?

**Comment by snarfed** [comment] 2024-12-15 23:22
Yeah, the unhappy follow here is you => jskharay, not you => the bot user. And odd, looking at https://fed.brid.gy/ap/@beetle_b@mastodon.xyz and our internal logs, mastodon.xyz again delivered us your new unfollow *after* your new follow. ActivityPub doesn't have a way to specify dependencies between activities, at least not these, so the last one generally wins. Looks like this is what happened last time too.

I guess try unfollowing jskharay, then wait an hour or so, then re-follow?

Disappointing that mastodon.xyz is this brittle. 😕

**Comment by beetleb** [comment] 2024-12-16 00:25
OK. I tried an unfollow, and waited about an hour and did a follow. Now it is showing me as a follower.

I'll await his next public post to see if I'll receive it.

**Comment by Tamschi** [comment] 2024-12-16 18:30
> Disappointing that mastodon.xyz is this brittle. 😕

Technically this is a bit of a protocol violation in Bridgy Fed. It's supposed to persist the `@id` of the `Follow` and then [check against that](https://github.com/mastodon/mastodon/blob/efe4e72f934581749ced193672df04cd2d891508/app/lib/activitypub/activity/undo.rb#L47) when `Undo`ing it.
However, [Mastodon seemingly also doesn't do this properly when the object is inlined](https://github.com/mastodon/mastodon/blob/efe4e72f934581749ced193672df04cd2d891508/app/lib/activitypub/activity/undo.rb#L89-L101).

(If there was a significant time difference between the activities, then reordering is likely caused by network or other load issues at mastodon.xyz though, yes.)

**Comment by beetleb** [comment] 2024-12-16 18:57
And his most recent post showed up in my feed!

Thanks for the help debugging. Feel free to close this if you need to.

**Comment by Tamschi** [comment] 2024-12-16 19:01
I'll close it. There's an underlying Bridgy Fed bug here in my opinion, but that now has a distinct issue.

Thanks for letting us know this particular instance of the issue is resolved!

**Closed by Tamschi** 2024-12-16 19:01 UTC
Labels: bug

**Comment by snarfed** [comment] 2024-12-16 20:57
> Technically this is a bit of a protocol violation in Bridgy Fed. It's supposed to persist the `@id` of the [most recent, at least] `Follow` and then [check against that](https://github.com/mastodon/mastodon/blob/efe4e72f934581749ced193672df04cd2d891508/app/lib/activitypub/activity/undo.rb#L47) when `Undo`ing it. 

Great point! I'd forgotten `id`, that absolutely works for `Undo`s of activities with ids. It doesn't work if the object being undone is transient, but I expect that's not true here.
