### ISSUE TITLE
Flipboard posts to Bluesky don't show URL image

### ISSUE THREAD

**Issue by Steviemac1** [snarfed/bridgy-fed#1522] opened 2024-11-19 19:10 UTC
Hi there,

I’ve got a feed from my Flipboard account going across to Bluesky. The posts appear on Bluesky, they all contain a url for an article on a web page which has been flipped into a flip oard magazine.

But they look pretty dull as posts in Bluesky. The url doesn't present as an image in the post there. I don’t know if that's working as designed, or something that can be fixed at either Bluesky end or at Flipboard. 

See @Ayethatllbright.flipboard.com.ap.brid.gy as the example.

**Comment by snarfed** [comment] 2024-11-20 00:23
Yes! This is #1411

**Comment by snarfed** [comment] 2024-11-20 00:24
Duplicate of #1411

**Closed by snarfed** 2024-11-20 00:24 UTC
